[theme]
primaryColor = "#4A90E2"
backgroundColor = "#242831"
secondaryBackgroundColor = "#323640"
textColor = "#E0E0E0"
font = "sans serif"

# ✅ Use polling so Streamlit Cloud doesn't hit the inotify limit
[server]
fileWatcherType = "poll"

# ✅ (Optional) reduce what Streamlit watches for changes
[global]
folderWatchBlacklist = ["venv", ".git", ".streamlit", "data", "node_modules"]
